### ISSUE TITLE
Home Assistant shows my alarm not armed when it is

### ISSUE THREAD

**Issue by jshank** [BioSehnsucht/ha-elkm1#1]
ha-elkm1 commit a5ac1b4a06d3a9caeb057bb92925a573135a8e82
hass 0.56.2 (docker image from 10/23)

Let me know the best way to capture additional debug information. I'm just getting the update failures below. Could this have anything to do with 2 systems connected to the M1EXP (Hass and ISY994i)?

Relavant logs

```
hass_1  | 2017-10-26 08:30:59 INFO (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=alarm_control_panel.elk_area_1, old_state=<state alarm_control_panel.elk_area_1=disarmed; code_format=[0-9]{4}([0-9]{2})?, changed_by=None, Readiness=Ready To Arm, but a zone violated and can be Force Armed, Status=Disarmed, State=disarmed, Alarm=No Alarm Active, friendly_name=Home, last_armed_by_user=0, last_armed_at=0, last_disarmed_by_user=0, last_disarmed_at=0, last_user_code=3, last_user_at=1509031859.0975542 @ 2017-10-25T20:43:55.484215-07:00>, new_state=<state alarm_control_panel.elk_area_1=armed_away; code_format=[0-9]{4}([0-9]{2})?, changed_by=None, Readiness=Force Armed with a force arm zone violated, Status=Armed Away, State=armed_away, Alarm=No Alarm Active, friendly_name=Home, last_armed_by_user=3, last_armed_at=1509031859.1385984, last_disarmed_by_user=0, last_disarmed_at=0, last_user_code=3, last_user_at=1509031859.0975542 @ 2017-10-26T08:30:59.141489-07:00>>
hass_1  | 2017-10-26 08:30:59 ERROR (MainThread) [homeassistant.helpers.entity] Update for alarm_control_panel.elk_area_1 fails
hass_1  | 2017-10-26 08:30:59 ERROR (MainThread) [homeassistant.helpers.entity] Update for alarm_control_panel.elk_area_1 fails
...

```

config

```
elkm1:
  host: socket://10.1.10.21:2101
  code: !secret elk_pin
  area:
    exclude: 2-8
  output:
    exclude: 4-208
  task:
    exclude: 1-32
  thermostat:
    exclude: 1-16
  x10:
    exclude: a1-p16
  counter:
    exclude: 1-64
  keypad:
    exclude: 3-16
  zone:
    exclude: 12-208
```
