### ISSUE TITLE
Problems with new install and setup

### ISSUE THREAD

**Issue by sjthespian** [BioSehnsucht/ha-elkm1#11]
I have installed ha-elkm1 on my hass.io system (via git clone) and have run into a couple of issues getting it up and running.

For starters, here is my configuration:
```
elkm1:
  host: socket://xxx.xxx.xxx.xxx:2101
  area:
    exclude: 2-8
  zone:
    exclude: 25-160, 165-208
  keypad:
    exclude: 5-16
  task:
    exclude: 1-32
  counter:
    enabled: false
    exclude: 1-64
  output:
    enabled: false
    exclude: 1-208
  thermostat:
    enabled: false
    exclude: 1-16
  x10:
    enabled: false
    exclude: a1-p16
```

I'm trying to exclude everything except area 1, my zones that are in use, and a couple of keypads since that's all I'm really interested in at the moment. However, I still end up with all of the outputs and tasks on my HA dashboard. I've tried various combinations of enabled and exclude options with no luck.

I am also not getting area 1 on my dashboard, however I *do* have area 2 showing up. I'm also not seeing any keypads, how should those be showing up on the dashboard?

The zones show up, but they aren't recording any history, is that expected? I was hoping to get history so I can track movement around the house via. the motion sensors.

Any idea what's going on?
