### ISSUE TITLE
Lost friendly name

### ISSUE THREAD

**Issue by jshank** [BioSehnsucht/ha-elkm1#4]
I'm on 0.63.1 and I've lost the friendly_name mapping from the Elk M1G, it used to show Front Door but now shows elk_zone_001. Instead of Home it shows elk_area_1

**Comment by BioSehnsucht** [comment]
Does everything else appear to work? Did other friendly names stay the same?

Is this a friendly name you set in HASS, or was this the description set in the Elk panel for the zone?

**Comment by jshank** [comment]
All friendly names were lost. They came from the Elk system itself and not from customize.yaml. Zones still trigger properly but armed status is lost after the first refresh (same as #1 ).

**Comment by BioSehnsucht** [comment]
Do the names appear at first when you restart HASS, or do they not even appear briefly anymore?

**Comment by jshank** [comment]
They never appear in the system, they are just named elk_defaultname.xxx. I'm running a git pull from 2/17 a5ac1b4a06d3a9caeb057bb92925a573135a8e82

` 2018-02-19 10:11:26 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.elkm1`
`2018-02-19 10:11:26 INFO (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=sensor.elk_zone_001, old_state=None, new_state=<state sensor.elk_zone_001=Normal; hidden=False, Status=Normal, State=EOL, Alarm=Disabled, Definition=Burglar Entry/Exit 1, friendly_name=elk_zone_001, icon=mdi:alarm-bell @ 2018-02-19T10:11:26.875588-08:00>>`

```yaml
elkm1:
  host: socket://10.1.1.1:2101
  area:
    exclude: 2-8
  output:
    exclude: 4-208
  task:
    exclude: 1-32
  thermostat:
    exclude: 1-16
  x10:
    exclude: a1-p16
  counter:
    exclude: 1-64
  keypad:
    exclude: 3-16
  zone:
    exclude: 12-208
```
