### ISSUE TITLE
Errors on Startup

### ISSUE THREAD

**Issue by DamianFlynn** [BioSehnsucht/ha-elkm1#5]
[home-assistant.ELKM1_InitialStart.log](https://github.com/BioSehnsucht/ha-elkm1/files/1851581/home-assistant.ELKM1_InitialStart.log)
[home-assistant.ELKM1_SecondStart.log](https://github.com/BioSehnsucht/ha-elkm1/files/1851582/home-assistant.ELKM1_SecondStart.log)
[home-assistant.ELKM1_FullReset.log](https://github.com/BioSehnsucht/ha-elkm1/files/1851583/home-assistant.ELKM1_FullReset.log)

On a Clean HassIO installation, with the new 0.2.0 release, my configuration file hosts the following settings. 

Essentially, I want support for Zones, Outputs, and Alarm Functions; nothing more:

```yaml
elkm1:
  host: socket://172.16.1.253:2101
  fastload: true
  area:
    exclude: 2-8
  zone:
    enabled: true
    autohide: false
  output:
    exclude: 1-32, 41-208
  task:
    exclude: 1-32
  x10:
    exclude: a1-p16
  thermostat:
    exclude: 1-16
  counter:
    exclude: 1-64
  keypad:
    exclude: 2-16
  setting:
    exclude: 1-16
  user:
    exclude: 5-200
```

Tailing the log, I can see that the exclusions are ignored, and warnings are been issued for setup of the platform taking beyond 10 seconds, listing off all the components, For example - these are samples for the `home-assistant.log`

```yaml
2018-03-27 10:30:02 WARNING (MainThread) [homeassistant.components.climate] Setup of platform elkm1 is taking over 10 seconds.
2018-03-27 10:30:02 WARNING (MainThread) [homeassistant.components.sensor] Setup of platform elkm1 is taking over 10 seconds.
2018-03-27 10:30:02 WARNING (MainThread) [homeassistant.components.alarm_control_panel] Setup of platform elkm1 is taking over 10 seconds.
2018-03-27 10:30:07 WARNING (MainThread) [homeassistant.components.switch] Setup of platform elkm1 is taking over 10 seconds.
018-03-27 10:30:11 WARNING (MainThread) [homeassistant.components.light] Setup of platform elkm1 is taking over 10 seconds.
```

The solution takes 71 seconds to load, and appear to timeout retrieving all the friendly names for the sensors. After startup it also appears that the events are not been fired, for example motion.

I have a debug log, at 3Mb for this 90 seconds of startup, to help illustrate this scenario.

For subsequent start-up, with fast load enabled, the intialized completes in 46 seconds; however I continue to see the errors, for example max pending messages, and a bunch of associated exceptions will present a few moments after. 

This time, I will only be presented with Outputs, and no Zones for example.

Second clean log is available.

Going to run a few more tests, deleting the Home-Assistant.log. Home-Assistant_v2.db, and PyElkFastload; that log is also attached.

You will see inconsistent issues here again - Events not firing; in the Dev view, a couple of keypad temps, ELK Settings, and zones autohidden and missing the real friendly names.

I can grant you SSH to the host if that will help, where you are welcome to reset and debug at will.
Damian
