### ISSUE TITLE
sensor.elk_area_1_last_user_at

### ISSUE THREAD

**Issue by DamianFlynn** [BioSehnsucht/ha-elkm1#6]
While enumerating the states list in the the dev tools, the above sensor is not been presented currently?

I have created the sensor with the following guidance

```yaml

sensor:

  - platform: template
    sensors:
      elk_area_1_last_user_at:
        value_template: '{{ states.alarm_control_panel.elk_area_1.attributes.last_user_at }}'
        friendly_name: 'ELK Area 1 last accessed at'#

```

Closing issue, as this appears to be related to a problem noted in #5 with events and refreshing.
