### ISSUE TITLE
Configuration Error: Included "outputs" are off by 1

### ISSUE THREAD

**Issue by jshank** [BioSehnsucht/ha-elkm1#9]
Referring to [gwww branch](/BioSehnsucht/ha-elkm1/tree/gwww-elkm1-lib) 
In `configuration.yaml`

```
elkm1:
  host: elk://192.168.0.1:2101 
  output:
    include:
      - 2

```
renders `switch.elkm1_output_003` available (one output greater the included output)
